<?php
require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/auth.php';
require_once __DIR__ . '/includes/functions.php';

requireRole('admin');

if (!isset($_GET['id']) || !is_numeric($_GET['id'])) {
    header("Location: " . base_url('admin_cases.php'));
    exit();
}

$case_id = (int)$_GET['id'];

$stmt = $pdo->prepare("
    SELECT wc.*, u.name as student_name, c.name as counselor_name 
    FROM wellness_cases wc
    LEFT JOIN users u ON wc.student_id = u.id
    LEFT JOIN users c ON wc.assigned_counselor_id = c.id
    WHERE wc.id = ?
");
$stmt->execute([$case_id]);
$case = $stmt->fetch();

if (!$case) {
    $_SESSION['error_message'] = "Case not found.";
    header("Location: " . base_url('admin_cases.php'));
    exit();
}

// Notes
$stmt = $pdo->prepare("SELECT cn.*, u.name as author_name FROM case_notes cn JOIN users u ON cn.counselor_id = u.id WHERE cn.case_id = ? ORDER BY cn.created_at DESC");
$stmt->execute([$case_id]);
$notes = $stmt->fetchAll();

// Get counselors for reassignment dropdown
$stmt = $pdo->query("SELECT id, name FROM users WHERE role = 'counselor' ORDER BY name ASC");
$counselors = $stmt->fetchAll();

$student_display = ($case['support_mode'] === 'anonymous') ? 'Anonymous Student' : htmlspecialchars($case['student_name']);

require_once __DIR__ . '/includes/header.php';
?>

<div class="container-fluid">
    <div class="row mb-4">
        <div class="col-12 d-flex justify-content-between align-items-center">
            <div>
                <h2>Supervise Request #<?php echo $case['id']; ?></h2>
                <span class="badge bg-secondary"><?php echo ucfirst($case['category']); ?></span>
                <?php if ($case['escalation_flag']): ?>
                    <span class="badge bg-danger">Escalated</span>
                <?php endif; ?>
            </div>
            <div>
                <a href="<?php echo base_url('print_report.php?case_id=' . $case_id); ?>" class="btn btn-outline-secondary me-2" target="_blank">Print Case</a>
                <a href="<?php echo base_url('admin_cases.php'); ?>" class="btn btn-outline-secondary">Back to Cases</a>
            </div>
        </div>
    </div>

    <div class="row">
        <!-- Left Column: Case Details & AI -->
        <div class="col-md-7">
            <div class="card shadow-sm border-0 mb-4">
                <div class="card-header bg-white d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Student Concern Details</h5>
                    <span class="badge bg-<?php echo $case['urgency'] == 'high' ? 'danger' : ($case['urgency'] == 'medium' ? 'warning' : 'info'); ?>">
                        Urgency: <?php echo ucfirst($case['urgency']); ?>
                    </span>
                </div>
                <div class="card-body">
                    <h6 class="card-title fw-bold"><?php echo htmlspecialchars($case['title']); ?></h6>
                    <p class="mb-3"><?php echo nl2br(htmlspecialchars($case['description'])); ?></p>
                    
                    <hr>
                    <div class="row small text-muted">
                        <div class="col-sm-4"><strong>Student:</strong> <?php echo $student_display; ?></div>
                        <div class="col-sm-4"><strong>Mode:</strong> <?php echo ucwords(str_replace('_', ' ', $case['support_mode'])); ?></div>
                        <div class="col-sm-4"><strong>Date:</strong> <?php echo date('M d, Y H:i', strtotime($case['created_at'])); ?></div>
                    </div>
                </div>
            </div>

            <!-- AI Intelligence Review Panel -->
            <div class="card shadow-sm border-0 mb-4 border-start border-primary border-4">
                <div class="card-header bg-white d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">AI Intelligence Review</h5>
                    <small class="text-muted">Generated by Counselor</small>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <strong>AI Risk Pattern:</strong> 
                        <span class="badge bg-<?php echo in_array($case['ai_risk_pattern'], ['high', 'critical']) ? 'danger' : 'secondary'; ?>">
                            <?php echo $case['ai_risk_pattern'] ? ucfirst($case['ai_risk_pattern']) : 'Not generated'; ?>
                        </span>
                    </div>
                    <div class="mb-3">
                        <strong>Counselor-Facing Summary:</strong>
                        <div class="bg-light p-2 rounded mt-1 small">
                            <?php echo $case['ai_summary'] ? nl2br(htmlspecialchars($case['ai_summary'])) : '<span class="text-muted">Not generated</span>'; ?>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Notes Timeline -->
            <div class="card shadow-sm border-0 mb-4">
                <div class="card-header bg-white">
                    <h5 class="mb-0">Case Notes History</h5>
                </div>
                <div class="card-body p-0">
                    <?php if (count($notes) > 0): ?>
                        <ul class="list-group list-group-flush">
                            <?php foreach ($notes as $note): ?>
                                <li class="list-group-item p-3">
                                    <div class="d-flex justify-content-between align-items-center mb-2">
                                        <span class="fw-bold"><?php echo htmlspecialchars($note['author_name']); ?></span>
                                        <span class="badge bg-<?php echo $note['note_type'] == 'internal' ? 'secondary' : 'primary'; ?>">
                                            <?php echo ucwords(str_replace('_', ' ', $note['note_type'])); ?>
                                        </span>
                                    </div>
                                    <p class="mb-1 small"><?php echo nl2br(htmlspecialchars($note['note'])); ?></p>
                                    <small class="text-muted"><?php echo date('M d, Y h:i A', strtotime($note['created_at'])); ?></small>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php else: ?>
                        <div class="p-4 text-center text-muted">No notes recorded yet.</div>
                    <?php endif; ?>
                </div>
            </div>

        </div>

        <!-- Right Column: Admin Actions -->
        <div class="col-md-5">
            <!-- Assignment & Status Form -->
            <div class="card shadow-sm border-0 mb-4 border-start border-warning border-4">
                <div class="card-header bg-white">
                    <h5 class="mb-0">Supervisory Override</h5>
                </div>
                <div class="card-body">
                    <form method="POST" action="<?php echo base_url('admin_action.php'); ?>">
                        <input type="hidden" name="action" value="override_case">
                        <input type="hidden" name="case_id" value="<?php echo $case_id; ?>">
                        
                        <div class="mb-3">
                            <label class="form-label">Assign / Reassign Counselor</label>
                            <select name="assigned_counselor_id" class="form-select">
                                <option value="">-- Unassigned --</option>
                                <?php foreach ($counselors as $c): ?>
                                    <option value="<?php echo $c['id']; ?>" <?php echo $case['assigned_counselor_id'] == $c['id'] ? 'selected' : ''; ?>>
                                        <?php echo htmlspecialchars($c['name']); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>

                        <div class="mb-3">
                            <label class="form-label">Force Status Update</label>
                            <select name="status" class="form-select">
                                <?php
                                $statuses = ['submitted', 'under review', 'assigned', 'in progress', 'resolved', 'closed'];
                                foreach ($statuses as $st) {
                                    $sel = ($case['status'] == $st) ? 'selected' : '';
                                    echo "<option value=\"$st\" $sel>".ucfirst($st)."</option>";
                                }
                                ?>
                            </select>
                        </div>

                        <div class="form-check form-switch mb-4">
                            <input class="form-check-input" type="checkbox" name="escalation_flag" id="escFlag" value="1" <?php echo $case['escalation_flag'] ? 'checked' : ''; ?>>
                            <label class="form-check-label text-danger fw-bold" for="escFlag">Flag as Escalated Case</label>
                        </div>

                        <button type="submit" class="btn btn-warning w-100 fw-bold">Apply Overrides</button>
                    </form>
                </div>
            </div>

            <!-- Add Admin Note -->
            <div class="card shadow-sm border-0 mb-4">
                <div class="card-header bg-white">
                    <h5 class="mb-0">Add Supervisory Note</h5>
                </div>
                <div class="card-body">
                    <form method="POST" action="<?php echo base_url('admin_action.php'); ?>">
                        <input type="hidden" name="action" value="add_admin_note">
                        <input type="hidden" name="case_id" value="<?php echo $case_id; ?>">
                        
                        <div class="mb-3">
                            <textarea name="note" class="form-control" rows="3" required placeholder="Type an internal admin note..."></textarea>
                        </div>
                        <p class="small text-muted">Admin notes are always internal and invisible to students.</p>
                        <button type="submit" class="btn btn-secondary w-100">Add Note</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require_once __DIR__ . '/includes/footer.php'; ?>
